<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class Countries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["code" => "NG", "name" => "Nigeria"],
            ["code" => "AF", "name" => "Afghanistan"],
            ["code" => "AL", "name" => "Albania"],
            ["code" => "DZ", "name" => "Algeria"],
            ["code" => "AS", "name" => "American Samoa"],
            ["code" => "AD", "name" => "Andorra"],
            ["code" => "AO", "name" => "Angola"],
            ["code" => "AI", "name" => "Anguilla"],
            ["code" => "AQ", "name" => "Antarctica"],
            ["code" => "AG", "name" => "Antigua and Barbuda"],
            ["code" => "AR", "name" => "Argentina"],
            ["code" => "AM", "name" => "Armenia"],
            ["code" => "AW", "name" => "Aruba"],
            ["code" => "AU", "name" => "Australia"],
            ["code" => "AT", "name" => "Austria"],
            ["code" => "AZ", "name" => "Azerbaijan"],
            ["code" => "BS", "name" => "Bahamas"],
            ["code" => "BH", "name" => "Bahrain"],
            ["code" => "BD", "name" => "Bangladesh"],
            ["code" => "BB", "name" => "Barbados"],
            ["code" => "BY", "name" => "Belarus"],
            ["code" => "BE", "name" => "Belgium"],
            ["code" => "BZ", "name" => "Belize"],
            ["code" => "BJ", "name" => "Benin"],
            ["code" => "BM", "name" => "Bermuda"],
            ["code" => "BT", "name" => "Bhutan"],
            ["code" => "BO", "name" => "Bolivia"],
            ["code" => "BA", "name" => "Bosnia-Herzegovina"],
            ["code" => "BW", "name" => "Botswana"],
            ["code" => "BV", "name" => "Bouvet Island"],
            ["code" => "BR", "name" => "Brazil"],
            ["code" => "IO", "name" => "British Indian Ocean Territory"],
            ["code" => "BN", "name" => "Brunei Darussalam"],
            ["code" => "BG", "name" => "Bulgaria"],
            ["code" => "BF", "name" => "Burkina Faso"],
            ["code" => "BI", "name" => "Burundi"],
            ["code" => "KH", "name" => "Cambodia"],
            ["code" => "CM", "name" => "Cameroon"],
            ["code" => "CA", "name" => "Canada"],
            ["code" => "CV", "name" => "Cape Verde"],
            ["code" => "KY", "name" => "Cayman Islands"],
            ["code" => "CF", "name" => "Central African Republic"],
            ["code" => "TD", "name" => "Chad"],
            ["code" => "CL", "name" => "Chile"],
            ["code" => "CN", "name" => "China"],
            ["code" => "CX", "name" => "Christmas Island"],
            ["code" => "CC", "name" => "Cocos (Keeling) Islands"],
            ["code" => "CO", "name" => "Colombia"],
            ["code" => "KM", "name" => "Comoros"],
            ["code" => "CG", "name" => "Congo"],
            ["code" => "CK", "name" => "Cook Islands"],
            ["code" => "CR", "name" => "Costa Rica"],
            ["code" => "HR", "name" => "Croatia"],
            ["code" => "CU", "name" => "Cuba"],
            ["code" => "CY", "name" => "Cyprus"],
            ["code" => "CZ", "name" => "Czech Republic"],
            ["code" => "DK", "name" => "Denmark"],
            ["code" => "DJ", "name" => "Djibouti"],
            ["code" => "DM", "name" => "Dominica"],
            ["code" => "TL", "name" => "East Timor"],
            ["code" => "EC", "name" => "Ecuador"],
            ["code" => "EG", "name" => "Egypt"],
            ["code" => "SV", "name" => "El Salvador"],
            ["code" => "GQ", "name" => "Equatorial Guinea"],
            ["code" => "ER", "name" => "Eritrea"],
            ["code" => "EE", "name" => "Estonia"],
            ["code" => "ET", "name" => "Ethiopia"],
            ["code" => "FK", "name" => "Falkland Islands (Malvinas)"],
            ["code" => "FO", "name" => "Faroe Islands"],
            ["code" => "FJ", "name" => "Fiji"],
            ["code" => "FI", "name" => "Finland"],
            ["code" => "FR", "name" => "France"],
            ["code" => "GF", "name" => "French Guiana"],
            ["code" => "PF", "name" => "French Polynesia"],
            ["code" => "TF", "name" => "French Southern Territories"],
            ["code" => "GA", "name" => "Gabon"],
            ["code" => "GM", "name" => "Gambia"],
            ["code" => "GE", "name" => "Georgia"],
            ["code" => "DE", "name" => "Germany"],
            ["code" => "GH", "name" => "Ghana"],
            ["code" => "GI", "name" => "Gibraltar"],
            ["code" => "GR", "name" => "Greece"],
            ["code" => "GL", "name" => "Greenland"],
            ["code" => "GD", "name" => "Grenada"],
            ["code" => "GP", "name" => "Guadeloupe"],
            ["code" => "GU", "name" => "Guam"],
            ["code" => "GT", "name" => "Guatemala"],
            ["code" => "GN", "name" => "Guinea"],
            ["code" => "GW", "name" => "Guinea-Bissau"],
            ["code" => "GY", "name" => "Guyana"],
            ["code" => "HT", "name" => "Haiti"],
            ["code" => "HM", "name" => "Heard and McDonald Islands"],
            ["code" => "VA", "name" => "Vatican (Holy See)"],
            ["code" => "HN", "name" => "Honduras"],
            ["code" => "HK", "name" => "Hong Kong"],
            ["code" => "HU", "name" => "Hungary"],
            ["code" => "IS", "name" => "Iceland"],
            ["code" => "IN", "name" => "India"],
            ["code" => "ID", "name" => "Indonesia"],
            ["code" => "IR", "name" => "Iran"],
            ["code" => "IQ", "name" => "Iraq"],
            ["code" => "IE", "name" => "Ireland"],
            ["code" => "IL", "name" => "Israel"],
            ["code" => "IT", "name" => "Italy"],
            ["code" => "CI", "name" => "Ivory Coast"],
            ["code" => "JM", "name" => "Jamaica"],
            ["code" => "JP", "name" => "Japan"],
            ["code" => "JO", "name" => "Jordan"],
            ["code" => "KZ", "name" => "Kazakhstan"],
            ["code" => "KE", "name" => "Kenya"],
            ["code" => "KI", "name" => "Kiribati"],
            ["code" => "KP", "name" => "Korea (Democratic Republic of)"],
            ["code" => "KR", "name" => "Korea (Republic of)"],
            ["code" => "KW", "name" => "Kuwait"],
            ["code" => "KG", "name" => "Kyrgyz Republic"],
            ["code" => "LA", "name" => "Laos"],
            ["code" => "LV", "name" => "Latvia"],
            ["code" => "LB", "name" => "Lebanon"],
            ["code" => "LS", "name" => "Lesotho"],
            ["code" => "LR", "name" => "Liberia"],
            ["code" => "LY", "name" => "Libyan Arab Jamahiriya"],
            ["code" => "LI", "name" => "Liechtenstein"],
            ["code" => "LT", "name" => "Lithuania"],
            ["code" => "LU", "name" => "Luxembourg"],
            ["code" => "MO", "name" => "Macau"],
            ["code" => "MK", "name" => "Macedonia"],
            ["code" => "MG", "name" => "Madagascar"],
            ["code" => "MW", "name" => "Malawi"],
            ["code" => "MY", "name" => "Malaysia"],
            ["code" => "MV", "name" => "Maldives"],
            ["code" => "ML", "name" => "Mali"],
            ["code" => "MT", "name" => "Malta"],
            ["code" => "MH", "name" => "Marshall Islands"],
            ["code" => "MQ", "name" => "Martinique"],
            ["code" => "MR", "name" => "Mauritania"],
            ["code" => "MU", "name" => "Mauritius"],
            ["code" => "YT", "name" => "Mayotte"],
            ["code" => "MX", "name" => "Mexico"],
            ["code" => "FM", "name" => "Micronesia"],
            ["code" => "MD", "name" => "Moldavia"],
            ["code" => "MC", "name" => "Monaco"],
            ["code" => "MN", "name" => "Mongolia"],
            ["code" => "MS", "name" => "Montserrat"],
            ["code" => "MA", "name" => "Morocco"],
            ["code" => "MZ", "name" => "Mozambique"],
            ["code" => "MM", "name" => "Myanmar"],
            ["code" => "NA", "name" => "Namibia"],
            ["code" => "NR", "name" => "Nauru"],
            ["code" => "NP", "name" => "Nepal"],
            ["code" => "NL", "name" => "Netherlands"],
            ["code" => "AN", "name" => "Netherlands Antilles"],
            ["code" => "NC", "name" => "New Caledonia"],
            ["code" => "NZ", "name" => "New Zealand"],
            ["code" => "NI", "name" => "Nicaragua"],
            ["code" => "NE", "name" => "Niger"],
            ["code" => "NU", "name" => "Niue"],
            ["code" => "NF", "name" => "Norfolk Island"],
            ["code" => "MP", "name" => "Northern Mariana Islands"],
            ["code" => "NO", "name" => "Norway"],
            ["code" => "OM", "name" => "Oman"],
            ["code" => "PK", "name" => "Pakistan"],
            ["code" => "PW", "name" => "Palau"],
            ["code" => "PA", "name" => "Panama"],
            ["code" => "PG", "name" => "Papua-New Guinea"],
            ["code" => "PY", "name" => "Paraguay"],
            ["code" => "PE", "name" => "Peru"],
            ["code" => "PH", "name" => "Philippines"],
            ["code" => "PN", "name" => "Pitcairn"],
            ["code" => "PL", "name" => "Poland"],
            ["code" => "PT", "name" => "Portugal"],
            ["code" => "PR", "name" => "Puerto Rico"],
            ["code" => "QA", "name" => "Qatar"],
            ["code" => "DO", "name" => "Dominican Republic"],
            ["code" => "RE", "name" => "Reunion"],
            ["code" => "RO", "name" => "Romania"],
            ["code" => "RU", "name" => "Russian Federation"],
            ["code" => "RW", "name" => "Rwanda"],
            ["code" => "SH", "name" => "Saint Helena"],
            ["code" => "KN", "name" => "Saint Kitts and Nevis"],
            ["code" => "LC", "name" => "Saint Lucia"],
            ["code" => "PM", "name" => "Saint Pierre and Miquelon"],
            ["code" => "VC", "name" => "Saint Vincent and the Grenadines"]
        ];

        foreach($countries as $country){
            if(Nationality::where('code', $country['code'])->exists()){
                continue;
            }

            Nationality::create($country);
        }
        
    }
}
